### ISSUE TITLE
Question / Proposal: Framework integration

### ISSUE THREAD

**Issue by desyncr** [hirshagarwal/timeTrack#15]
In current modern PHP web development it's rare to find a plain old-school php project (such as this one), which are mostly found as legacy systems.

My idea is to implement timeTrack on a modern PHP web framework such as Laravel, Symfony, Silex or similar.
The project is in a very young age and a rewrite won't hinder it's development to a point of being neglected.

There are many benefits of using a web framework over plain old php. I won't cover them here but you can make a quick research and find it out yourself.

Other point to use a web framework is that the project as a whole would be more attractive to new comers and potential contributors (from new comers to the whole web dev world and also people interesting in learning a new framework - be it laravel, symfony, silex etc).

Cons about this approach is the required level of knowledge is actually a bit higher than the current one which would prevent people to contribute to core components.

This is a really quick write-up so if there is anything that is not clear let me know. I'm using the issue tracker to propose it so everyone involved in the project can have a voice in the discussion.

Thoughts?

**Comment by jamiewitter** [comment]
I'm learning from scratch and for fun so the framework is irrelevant to me.

**Comment by stewardc** [comment]
I think using a framework is the way to go.

**Comment by rbakken2504** [comment]
I'm learning php from scratch as well, so I would prefer a modern framework.

On Wednesday, July 23, 2014 7:27 PM, desyncr notifications@github.com wrote:

In current modern PHP web development it's rare to find a plain old-school php project (such as this one), which are mostly found as legacy systems.
My idea is to implement timeTrack on a modern PHP web framework such as Laravel, Symfony, Silex or similar.
The project is in a very young age and rewrite won't hinder it's development to a point of being neglected.
There are many benefits of using a web framework over plain old php. I won't cover them here but you can make a quick research and find it out yourself.
Other point to use a web framework is that the project as a whole would be more attractive to new comers and potential contributors (from new comers to the whole web dev world and also people interesting in learning a new framework (be it laravel, symfony, silex etc).
Cons about this approach is the required level of knowledge is actually a bit higher than the current one which would prevent people to contribute to core components.
This is a really quick write-up so if there is anything that is not clear let me know. I'm using the issue tracking to propose it so everyone involved in the project can have a voice on the discussion.
Thoughts?

**Comment by hirshagarwal** [comment]
Thanks for the input. I think that using a framework is a good idea. We have only really done work with legacy php stuff. Would you be willing to help lead the framework integration?

**Comment by desyncr** [comment]
@hirshagarwal I have mostly experience working with Symfony2, Silex and Zend2. Laravel, though, seems to be pretty heavily adopted and very popular with a huge community out there.

From my experience Laravel is well suited in our context due to the huge community and small learning curve.

:+1:  for Laravel

As soon as we agree on a framework to adopt I'll port the basic functionality in the current code base. I'm not sure how much time it'll take me but I believe it won't be more than two days. You can, meanwhile, keep working on the current code as usual.

Suggestions? Other options?

**Comment by hirshagarwal** [comment]
@desyncr After some research it appears that Laravel would, as you said, be well suited for our project. I think that this is without a doubt the way to go. 
So if you want to look into porting everything over to Laravel that would be great, however give it a day or so before you start just to give anybody who has any other suggestions some time to speak up. 

Thanks for the suggestion, I think this will be very helpful in the long run.
